spring:
    datasource:
        url: jdbc:h2:~/uniqapoc-test;DB_CLOSE_DELAY=5;DB_CLOSE_ON_EXIT=FALSE
        name:
        username: uniqapoc-test
        password:

server:
    port: 5001

uniqapoc:
    urlbase: http://test-uniqapoc.szoboszlai.eu
