spring:
    datasource:
        url: jdbc:h2:~/uniqapoc-prod;DB_CLOSE_DELAY=5;DB_CLOSE_ON_EXIT=FALSE
        name:
        username: uniqapoc-prod
        password:

server:
    port: 5000


uniqapoc:
    urlbase: http://prod-uniqapoc.szoboszlai.eu